### PR TITLE
Upgrade to Emscripten 1.37

### PR DESCRIPTION
**Pull request by hfmanson**
This pull request works with the newest zorba xquery processor which i forked from https://github.com/zorba-processor/zorba.git. I updated checkout.sh accordingly.

### CODE REVIEW

**Comment by wcandillon** [comment]
Can you show me how to use it?

**Comment by hfmanson** [comment]
Dear William,

Here are the instructions:
- run checkout.sh, this wil clone https://github.com/hfmanson/zorba.git
- run configure_zorba.sh, this is based on your build_zorba.sh script but
only the configuration part
- run buid_zorba.sh, this is based on your build_zorba.sh script but only
the 'make' part
- run install_zorba.sh, this is based on your build_zorba.sh script but
only the install part
- run build.sh this will build the (slightly adapted) example src/zorba.cpp
and produce zorba.html, zorba.html.mem and zorba.html.mem

When you copy these files to a webserver this is the result:
[image: Inline image 1]

Kind regards,

Henri Manson

On Sun, Apr 23, 2017 at 8:35 PM, William Candillon <notifications@github.com

**Comment by wcandillon** [comment]
@hfmanson sounds incredible! Do you have a use case for it or it is more like a fun project?

**Comment by hfmanson** [comment]
I've developed a SVG game engine using XQuery. On initialization a XML game
level is processed to produce SVG which has embedded the original level.
When a user action like keypresses or mouse actions takes place that action
is converted to XML along and send using XHR with the current board state
and processed again using XQuery to produce an XML file with 'commands'
like replacing XML nodes playing sounds etc. It would be nice to have an
schema-aware XQuery just in javascript. Then XHR will no longer be
necessary.

First I would like to polish this Pull Request. I'm only an Emscripten
beginner. I would like to implement an example containing XML and xquery
files.

On Sun, Apr 23, 2017 at 9:50 PM, William Candillon <notifications@github.com

**Comment by hfmanson** [comment]
P.S. do you still have the recipe to create emscipten libxml2?

**Comment by wcandillon** [comment]
@hfmanson sounds so cool (cc @fcavalieri). Unfortunately I forgot everything regarding emscripten

**Pull request merged**
